backend:
  name: git-gateway
  repo: MaximePrss19/SITE
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Page d'accueil"
        name: "index"
        file: "index.html"
        fields:
          - {label: "Titre", name: "title", widget: "string"}